openapi: 3.0.0
info:
  title: GaryWork API
  version: 0.1.0
servers:
  - url: http://localhost:3000/api
    description: Optional server description, e.g. Main (production) server
paths:
  /user/users:
    get:
      summary: Returns a list of all users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        '200':    # status code
          description: A JSON array of user data
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: object
               